
#document:
# root: C:/Users/ASUS/Desktop/jasper-demo # 改成自己的目录

#report:
# template:
#   path: classpath:jasper


#与 application.properties配置等价：
#document.root= C:/Users/ASUS/Desktop/jasper-demo
#report.template.path = classpath:jasper