# DataSource Config
spring:
  datasource:
    #h2数据源
    h2:
      driver-class-name: org.h2.Driver
      #schema: classpath:db/schema.sql
      #data: classpath:db/data.sql
      url: jdbc:h2:mem:test
      username: root
      password: test
    #mysql数据源
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456


mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto
  # 配置扫描通用枚举
  type-enums-package: com.example.demo.model.enums