DROP TABLE IF EXISTS user;

CREATE TABLE user(
    ID INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name CHAR(50) NULL,
    password CHAR(50) NULL,
    age INT(6) NOT NULL,
    gender CHAR(50) NULL,
    race CHAR(50) NULL
)